config/routes.rb
Rails.application.routes.draw do


  devise_for :users
 root to: 'homes#top'
 get 'home/about',to: "homes#about"
 get "search" => "searches#search"
 resources :users do
     resource :relationships, only: [:create, :destroy]
     get :followings, on: :member
     get :followers, on: :member
 end
 resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments,only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true,length: {maximum: 200}
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # 1:nの関係となる
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id,scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
#   コメントとuserはn:1となるため
has_many :relationships, foreign_key: :following_id
# フォローする側から伸びている

has_many :followings, through: :relationships, source: :follower
has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
has_many :followers, through: :reverse_of_relationships, source: :following
# user側で2回書いたのでここでもhas_manyを書くということ


   def already_favorited?(book)
     self.favorites.exists?(book_id: book.id)
   end

   def is_followed_by?(user)
     reverse_of_relationships.find_by(following_id: user.id).present?
   end
   
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where(" LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :name, presence: true,length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
   user_path(resource)
  end



end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  before_action :authenticate_user!
  # before_action :currect_user, only: [:destroy]
  # ログインしてるuserしか消せない

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id
    @comment.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.find(params[:id])
    @book_comment.destroy
    # Ajax処理
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @newbook = Book.new
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path, alert: 'Warring!!'
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
  # <!--Ajax処理追加-->
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    # <!--Ajax処理追加-->
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  # log inしてるuserしか出来ない

  def search
    @range = params[:range]
    # モデルを選択してそれを取ってきてる

    if @range == "User"
      @users = User.looks(params[:search],params[:word])
      # usermodel内の検索結果を代入する
    else
      # 検索Bookmodel
      @books = Book.looks(params[:search],params[:word])
      # Bookmodel内の検索結果を代入する
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.where.not(id: current_user.id)
    # 変更
    @book = Book.new
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    #@userに関連付けされたやつを@booksに渡している
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user),alert:'warring!!'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have created book successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def create
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
<% @book.book_comments.each do |book_comment| %>
  <p><%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(book_comment.user) %><br></p>
     <%= book_comment.user.name %>
     <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <p><%= link_to 'Delete', book_book_comment_path(book_comment.book, book_comment),class: "btn btn-danger", method: :delete, remote: true  %></p>
          <!--引数を二つ使う。rails routesで確認-->
          <!--Ajax処理実装-->
    <% end %>
    <% end %

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$('.book_comment').html("<%= j(render 'books/comment', book:@book ) %>");
$("book_comment_comment").val("");
<!--入力フォーム？-->

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$('.book_comment').html("<%= j(render 'books/comment', book:@book ) %>");
$("book_comment_comment").val("");
<!--入力フォーム？-->

app/views/books/_book.html.erb
<% if book.errors.any? %>
 <%= book.errors.count %>件のエラーが発生しました
 <% book.errors.full_messages.each do |message| %>
 <%= message %>
<% end %>
<% end %>

    <% if user_signed_in? %>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['User'], ['Book']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>

  <div class = "container px5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <h2>User info</h2>
         <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class = "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follwer</th>
              <th><%= link_to user.followings.count, followings_user_path(user) %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to user.followers.count, followers_user_path(user) %></th>
            </tr>
            <tr>
              <th>    
                <% if current_user != user %>
                <!--indexには必要ないかも？-->
                  <% if user.is_followed_by?(current_user) %>
                    <%= link_to user_relationships_path(user), method: :delete do %>
                    <button class = "btn btn-danger">フォロー解除</button>
                   <% end %>
                   <% else %>
                  <%= link_to user_relationships_path(user), method: :post do %>
                  <button class = "btn btn-primary">フォロー</button>
                   <% end %>
                  <% end %>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
         <div class = "row">
          <%= link_to "",edit_user_path(user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
         </div>

           <h2>New book</h2>
           <!--入力フォーム-->
           <%= form_with model: book,local: true do |f| %>
           　<%= f.label :title %><br>
           　<%= f.text_field :title %><br>
           　<%= f.label :Opinion %><br>
           　<%= f.text_area :body %>
           　<%= f.submit 'Create Book', class:"btn btn-success" %>
           <% end %>
      </div>
  <div class = "col-md-8 offset-md-1">

app/views/books/_comment.html.erb
<!--コメント作成機能-->

     <% book.book_comments.each do |book_comment| %>
        <tr>
        <td>
          <p><%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(book_comment.user) %><br></p>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
        </td>
          <td id="destroy_buttons<%= book_comment.id %>">
            <% if book_comment.user == current_user %>
          <p><%= link_to 'Delete', book_book_comment_path(book_comment.book, book_comment),class: "btn btn-danger", method: :delete, remote: true  %></p>
          <!--引数を二つ使う。rails routesで確認-->
          <!--Ajax処理実装-->
         <% end %>
          </td>
      　</td>
     </tr>
     <% end %>

app/views/books/_comments.html.erb
<!--削除ボタン-->

          <% if book_comment.user == current_user %>
          <p><%= link_to 'Delete', book_book_comment_path(book_comment.book, book_comment),class: "btn btn-danger", method: :delete, remote: true  %></p>
          <!--引数を二つ使う。rails routesで確認-->
          <!--Ajax処理実装-->
         <% end %>
         

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<% if flash[:notice] %>
<p class = "success"><%= flash[:notice] %></p>
<% end %>

<main>
  <div clas = "container">
    <div class = "row">
      <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
        <%= form_with model: @book,local: true do |f| %>

        <%= f.label :title %><br>
        <%= f.text_field :title %><br>

        <%= f.label :opinion %><br>
        <%= f.text_area :body %><br>

        <%= f.submit %><br>

        <%= link_to "Show",book_path(@book.id) %>
        <%= link_to "Back",books_path %>

        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<body>
<main>
<%= render 'books/book',books:@books,user:@user,book:@book %>
<!--テンプレート共通-->

<!--User一覧画面-->
　<h2>Books</h2>
　 <table class = "table" >
    <thead>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
   </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
       <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user.id) %>
      </td>
      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td id="favorite_buttons_<%= book.id %>">
        <%= render 'favorites/favorite', book:book %>
      </td>
    </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>
</main>
</body>

app/views/books/new.html.erb
<h1>New.htmlです</h1>

<%= form_for @book do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.submit %>

<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

<body>
<main>
<%= render 'books/book',books:@books,user:@user,book:@newbook %>

　　　　<!--User一覧画面-->
　　<h2>Book detail</h2>
　   <table class = "table" >
 　　　　 <thead>
   　    <th>image</th>
    　　<th>title</th>
    　　<th>body</th>
       </thead>
  <tbody>
    <tr id="book_<%= @book.id %>">
      <td>
       <%= link_to attachment_image_tag(@book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(@user.id) %><br>
       <%= link_to @user.name,user_path(@user.id) %>
      </td>
      <td><%= link_to @book.title,book_path(@book.id) %></td>
      <td><%= @book.body %></td>
      <td id="favorite_buttons_<%= @book.id %>">
        <%= render 'favorites/favorite', book:@book %>
      </td>
      <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>

      <% if @book.user.id == current_user.id %>
         <td><%= link_to "Edit",edit_book_path(@book.id),class: "button is btn btn-success" %></td>
         <td><%= link_to "Destroy", book_path(@book.id),class: "btn btn-danger", method: :delete, "data-confirm" => "Are you sure?" %></td>
      <% end %>
    </tr>

    </tbody>
   </table>
   <table class="book_comment">
       <%= render 'books/comment' , book:@book %>
   </table>
        <%= form_with(model:[@book, @book_comment]) do |f| %>
        <!--Ajax処理-->
        <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
        <% end %>
  </div>
 </div>
</div>

</body>

app/views/favorites/_favorite.html.erb
<!--いいね部分のテンプレート化-->

          <% if current_user.already_favorited?(book) %>
           <%= link_to book_favorites_path(book),method: :delete, remote: true do %>
           <!--Ajax処理追加-->
            <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
           <%= link_to book_favorites_path(book),method: :post, remote: true  do %>
           <!--Ajax処理追加-->
            <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <%= book.favorites.count %>
          

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

app/views/homes/top.html.erb
<body>
  <main>
    <p id = "notice"></p>
    <div class = "container">
      <div class = "mx-auto col-11 col-sm col-lg-8 col-xl-6">
        <h2>
          "welcome to"
          <i class = "fas fa-book">
            before
          </i>
          <string>Bookers</string>
           !!
        </h2>
        <p>
          "In"
          <i class="fas fa-book">
            before
          </i>
          <string>Bookers</string>
          , 
        </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class = "btn-wrapper col-10 mx-auto">
          <div class = "row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class = "row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
    <thead>
   　 <th>image</th>
   　<th>title</th>
   　<th>opinion</th>
    </thead>
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
        <td>
         <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        </td>
          <td><%= link_to user.name,user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
      <% @books.each do |book| %>
        <tr>
         <td>
          <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user.id) %>
         </td>
          <td><%= link_to book.title,book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<% if flash[:notice] %>
<p class = "success"><%= flash[:notice] %></p>
<% end %>

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<main>
  <div clas = "container">
    <div class = "row">
      <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user,local: true do |f| %>

        <%= f.label :name %><br>
        <%= f.text_field :name %><br>

        <%= f.label :image %><br>
        <%= f.attachment_field :profile_image %><br>

        <%= f.label :introduction %><br>
        <%= f.text_field :introduction %><br>

        <%= f.submit %>

        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/followers.html.erb</p>

<body>
 <main>
　<!--User一覧画面-->
　<h2>Follower Users</h2>
　 <table class = "table" >
 　　　　 <thead>
   　    <th>image</th>
    　　<th>name</th>
       </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
       <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.followings.count %></td>
      <td>フォロワー数:<%= user.followers.count %></td>
      <td><%= link_to "Show",user_path(user) %></td>
      <% end %>
    </tr>
    </tbody>
   </table>
  </main>
</body>

app/views/users/followings.html.erb
<h1>Users#followings</h1>
<p>Find me in app/views/users/followings.html.erb</p>

<body>
 <main>
　<!--User一覧画面-->
　<h2>Followings Users</h2>
　 <table class = "table" >
 　　　　 <thead>
   　    <th>image</th>
    　　<th>name</th>
       </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
       <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.followings.count %></td>
      <td>フォロワー数:<%= user.followers.count %></td>
      <td><%= link_to "Show",user_path(user) %></td>
      <% end %>
    </tr>
    </tbody>
   </table>
  </main>
</body>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<body>
<main>
  
<%= render 'books/book',books:@books,user:@user,book:@book %>
　<!--User一覧画面-->
　<h2>Users</h2>
　 <table class = "table" >
 　　　　 <thead>
   　    <th>image</th>
    　　<th>name</th>
       </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
       <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      </td>
      <td>
       <%= user.name %>
      </td>
      <td>
        <%= link_to "Show",user_path(user) %>
      </td>
      <% end %>
    </tr>
    </tbody>
   </table>
  </div>
 </div>
</div>
</body>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<body>
<main>


<%= render 'books/book',books:@books,user:@user,book:@book %>
<!--User一覧画面-->
　<h2>Books</h2>
　 <table class = "table" >
 　　　　 <thead>
   　    <th></th>
   　    <th>Title</th>
    　　  <th>Opinion</th>
       </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
       <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user.id) %>
      </td>
      <td><%= link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <% end %>
    </tr>
    </tbody>
   </table>
</body>