config/routes.rb
Rails.application.routes.draw do


  devise_for :users
 root to: 'homes#top'
 get 'home/about',to: "homes#about"
 get "search" => "searches#search"
 resources :users do
     resource :relationships, only: [:create, :destroy]
     get :followings, on: :member
     get :followers, on: :member
 end
 resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments,only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true,length: {maximum: 200}
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # 1:nの関係となる
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id,scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
#   コメントとuserはn:1となるため
has_many :relationships, foreign_key: :following_id
# フォローする側から伸びている

has_many :followings, through: :relationships, source: :follower
has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
has_many :followers, through: :reverse_of_relationships, source: :following
# user側で2回書いたのでここでもhas_manyを書くということ


   def already_favorited?(book)
     self.favorites.exists?(book_id: book.id)
   end

   def is_followed_by?(user)
     reverse_of_relationships.find_by(following_id: user.id).present?
   end
   
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where(" LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :name, presence: true,length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
   user_path(resource)
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @newbook = Book.new
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path, alert: 'Warring!!'
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
  # <!--Ajax処理追加-->
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    # <!--Ajax処理追加-->
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  # log inしてるuserしか出来ない

  def search
    @range = params[:range]
    # モデルを選択してそれを取ってきてる

    if @range == "User"
      @users = User.looks(params[:search],params[:word])
      # usermodel内の検索結果を代入する
    else
      # 検索Bookmodel
      @books = Book.looks(params[:search],params[:word])
      # Bookmodel内の検索結果を代入する
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.where.not(id: current_user.id)
    # 変更
    @book = Book.new
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    #@userに関連付けされたやつを@booksに渡している
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user),alert:'warring!!'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have created book successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def create
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d2945f0dfc.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!--ヘッダー部分-->


    <!--<ul class="nav navbar-nav navbar-right">-->
 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to "Home",user_path(current_user),class:"fas fa-home" %></li>
            <li><%= link_to "Users",users_path,class:"fas fa-users" %></li>
            <li><%= link_to "Books",books_path,class:"fas fa-book-open" %></li>
            <li><%= link_to "logout",destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt" %></li>
          <% else %>
            <li><%= link_to "Home",root_path,class:"fas fa-home" %></li>
            <li><%= link_to "about",home_about_path,class:"fas fa-link" %></li>
            <li><%= link_to "sign up",new_user_registration_path,class:"fas fa-user-plus" %></li>
            <li><%= link_to "login",new_user_session_path,class:"fas fa-sign-in-alt" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <!--</ul>-->

    <%= yield %>
    <!--各viewファイルがここで-->
  <footer>
   <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
     </div>
    </div>
  </footer>
  </body>
</html>